### ISSUE TITLE
oauth.Client relies on the disabled /certificate/sign endpoint

### ISSUE THREAD

**Issue by pjenvey** [mozilla/PyFxA#101]
`/certificate/sign` was recently disabled with the BrowserID removal from fxa, but the `oauth.Client` still uses this end point for getting a browserid assertion in its `authorize_code`.

Per @tarikeshaq, the Client
> may need to be updated to use the /oauth/authorization endpoint instead of the /v1/authorization for getting oauth codes (the latter seems to require a browser id assertion)
> https://mozilla.github.io/ecosystem-platform/api#tag/Oauth/operation/postAccountScopedkeydata

**Comment by vbudhram** [comment]
Thanks for filing @pjenvey, I think it will have to be updated to use https://mozilla.github.io/ecosystem-platform/api#tag/Oauth/operation/postOauthAuthorization

**Comment by clouserw** [comment]
This is tracked @ https://mozilla-hub.atlassian.net/browse/FXA-9538
