### ISSUE TITLE
Update library

### ISSUE THREAD

**Issue by jrconlin** [mozilla/PyFxA#103]
It appears that PyFxA hasn't been updated in quite some time. I note:

1) It is still supports Python 2 (even though that's been EoL for 4 years)
2) It uses outdated packages like `pytest-runner`, which notes [security issues](https://pypi.org/project/pytest-runner/).
3) It still relies on setuptools, which are deprecated and will not be supported very soon. 
etc.

We may wish to update the base requirement to Python3.8, which is scheduled for End of Life at [the end of 2024](https://devguide.python.org/versions/) This will mean [converting to a pyproject.toml file](https://packaging.python.org/en/latest/guides/modernize-setup-py-project/), updating libraries to more recent versions, dropping Python2 support and helper libraries, dropping BrowserID support, etc.

**Comment by clouserw** [comment]
Thanks to @robhudson we've migrated to project to pyproject.toml and ended python2 support.  We still use pytest-runner but I'm going to close this issue.

**Comment by robhudson** [comment]
Really I only worked on item 3 above, migrating from setup.py to pyproject.toml. 

For item 1: I removed the Python 2 classifiers but did not update the code in any way. Work should be done there to make things Python 3 centric. 

For item 2: I recommend adding in tox or hatch's built-in test environments to test across all supported Python 3.x versions. This is issue can be tracked in #105
