### ISSUE TITLE
Failure to receive verification email with creating an account

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/PyFxA#18]
I am suddenly seeing issues where, when I create an account, I am not receiving the verification email. I am calling `wait_for_email` in https://github.com/mozilla/PyFxA/blob/master/fxa/tests/utils.py#L99.

This is causing all of our tests which require an account to fail, so is a pretty high priority.

cc: @stephendonner

**Comment by bobsilverberg** [comment]
Note that this doesn't seem to have anything to do with changes for v0.0.5, as I'm seeing this issue with the old version we were using, which is 0.0.1.

Pinging @rfk and/or @jrgm for possible help!

**Comment by bobsilverberg** [comment]
Hmm, it seems to be fixed now, but it would be worthwhile seeing what caused it to try to ensure it doesn't happen again.

**Comment by jrgm** [comment]
@bobsilverberg - do you have the SMTP headers for the email that was delayed?

**Comment by rfk** [comment]
Was this using the production stack or a dev environment?

**Comment by bobsilverberg** [comment]
@jrgm Sorry, I don't have any info on the email.
@rfk It was using dev, i.e., https://stable.dev.lcip.org/auth/

**Comment by rfk** [comment]
OK, thanks.  It could easily have been some email-sending jank in the dev environment.  IIRC we have some rate-limiting and other stuff on our dev AWS SES account that we got removed for production-scale usage.

Let's keep an eye out for re-ocurrence but I don't think there's much more we can do with this particular bug.

**Comment by bobsilverberg** [comment]
Sounds good. Thanks @rfk
