### ISSUE TITLE
When using gevent, we need to use grequests instead of requests

### ISSUE THREAD

**Issue by Natim** [mozilla/PyFxA#21]
Add a way to define the requests driver to use in the apiclient.

https://github.com/mozilla/PyFxA/blob/master/fxa/_utils.py#L27-L28

**Comment by rfk** [comment]
This is part of the reason you can pass a custom `session` object into the APIClient constructor.  We may be able to find a neater solution though.

**Comment by Natim** [comment]
> This is part of the reason you can pass a custom session object into the APIClient

Ok I will investigate that then :)

**Comment by rfk** [comment]
It may be as simple as making a `grequests.Session()` object at the top-level and passing it in.  But I haven't tried to do that, it may turn out to be awkward or ugly in practice.

**Comment by Natim** [comment]
Closed with #22
