### ISSUE TITLE
Adding helpers to create Firefox Account and generate Bearer token and BrowserID assertions

### ISSUE THREAD

**Issue by Natim** [mozilla/PyFxA#35]
Following this article: http://www.servicedenuages.fr/en/load-testing-a-http-api-which-uses-oauth-for-authentication

I have been starting to work on tools to help load-testing with Firefox Account.

So far I have two command that let you write down a bearer token in a bash file (in order to export it in the environment to then load it)

The gist of the idea is there: https://gist.github.com/Natim/f4b1be4dde6eff8adaf2

What do you think about adding those helpers to PyFxA?
Should I put the function only (``create_new_user, get_bearer_token``)? Add the commands as well (``bin/create_new_user_token loadtest_salt``, ``bin/get_bearer_token email password``)?
Do you want a specific file architecture for that? (fxa.commands.get_bearer_token)

In that case I would refactor the plugin to use functions that would be shared with the CLI tools.

**Comment by Natim** [comment]
f? @rfk @almet

**Comment by rfk** [comment]
Sounds good to me.  I wonder if the following architecture makes sense:

* A single runner for all commands, e.g. `./bin/fxa-client create_new_user` and `./bin/fxa-client get_bearer_token`
* Each command implemented as you suggest in modules under an `fxa.commands` or `fxa.cli` 
package
* And make it so each command could also be imported and run by other helper tools if necessary

**Comment by rfk** [comment]
Assigning to @almet for further feedback

**Comment by Natim** [comment]
Thanks @rfk, @almet told me on IRC that he agrees. I like the idea of having subcommands. A PR will follow shortly :+1:

**Comment by Natim** [comment]
Superseeded by https://github.com/mozilla/PyFxA/pull/36
