### ISSUE TITLE
OAuthClient doesn't cache error responses

### ISSUE THREAD

**Issue by glasserc** [mozilla/PyFxA#46]
[The calls to cache.set](https://github.com/mozilla/PyFxA/blob/f7c972b4aa4bd5d0443e8a3aa06313ac38877c3a/fxa/oauth.py#L198-L199) happen only in the "happy path" when we've successfully verified a token. If we fail to verify a token for any reason, we usually throw an exception, which passes outside this control flow path. Some types of exception are probably indicative of a transient failure that we should retry, like a network failure, but other types represent rejected tokens (like this [OutOfProtocolError](https://github.com/mozilla/PyFxA/blob/f7c972b4aa4bd5d0443e8a3aa06313ac38877c3a/fxa/oauth.py#L188-L191)), and those responses should maybe be cached too to minimize network traffic in the future.

**Comment by shane-tomlinson** [comment]
@rfk - can you triage this one?

**Comment by vbudhram** [comment]
from mtg: closing for now
