### ISSUE TITLE
Should the token verification crash if the cache raises an exception?

### ISSUE THREAD

**Issue by leplatrem** [mozilla/PyFxA#48]
Currently, a failing cache prevents the OAuth verification to complete. Shouldn't it just fail to cache the response instead?

In other words, shouldn't we catch any exception during `cache.set()` ?

**Comment by rfk** [comment]
I'm in two minds about this - if the cache is routinely failing in production, you almost certainly want to know about it.  But a low-level lib like PyFxA is not in a good position to decide on the best policy.  We could throw, we could log a warning, or we could silence it completely, but I'm not sure any of those is the "right thing" in all cases.

One option, if ignoring errors is indeed the right thing for your use-case, may be to make a custom 
`Cache` instance with the desired behaviour that can e.g. log warnings as appropriate.

**Comment by leplatrem** [comment]
I agree, I'll make the change in the `Cache` class that we provide. It sounds obvious now :)

Thanks for taking the time to answer!
