### ISSUE TITLE
Strange user agent Python Requests 2.13

### ISSUE THREAD

**Issue by ghost** [mozilla/PyFxA#53]
When using PyFxa, I can't set User agent even trying to overwrite value by:
fxa_client.apiclient.headers["User-Agent"] = "Eolie-Web-Browser"

In Firefox account console, I see only Python Requests 2.13.

In _utils.py, I see Fxa should set a custom user agent.

**Comment by rfk** [comment]
Looking at that code in `_utils.py`, I think we always end up specifying a user-agent header in the call to `self._session.request(headers=headers)`, so this overrides any custom header values you've set on the `apiclient` object.  The code in `_utils.py` should instead:

* Look for a "user-agent" header in the `headers` parameter passed to the request.
* Look for a "user-agent" header in the `headers` property of `self._session`
* Only set the default header if it wasn't present in either of those places.

**Comment by philbooth** [comment]
@rfk, can you triage?

**Comment by vladikoff** [comment]
reopen if this will ever be needed
