### ISSUE TITLE
Implement the PKCE flow

### ISSUE THREAD

**Issue by Natim** [mozilla/PyFxA#58]
```
fxa-client --bearer --oauth-server https://oauth-latest-keys.dev.lcip.org/v1 \
                --scopes "profile https://identity.mozilla.org/apps/notes" --client-id abcd -c
ERROR:fxa-client:Public clients require PKCE OAuth parameters
```

**Comment by Natim** [comment]
I guess we need to pass the public_key in order to grab the keys back from the flow.

**Comment by rfk** [comment]
This may actually be a bug in the oauth-server; this script uses the `authorize_token` endpoint to directly exchange a BID assertion for an OAuth token, so it shouldn't need to go through the intermediate PKCE-flow stuff.

We should also add support for PKCE and the keyfetching stuff in PyFxA, I'm just surprised to see it causing an error in this particular flow.

**Comment by rfk** [comment]
> this script uses the authorize_token endpoint to directly exchange a BID assertion for an OAuth token

Actually, only certain client IDs are allowed to use this flow anyway, and PKCE clients probably shouldn't be among them.  So you're right @Natim, we need to extend this script to allow fetching tokens for publicClients via PKCE.
