### ISSUE TITLE
API names confusion

### ISSUE THREAD

**Issue by tarekziade** [mozilla/PyFxA#6]
I am confused by the oauth Client method names.

in trade_code,  what is "code". Is it the session token issued during the connection or something else ?

there are several spots where "code" and "token" are used to describe the same thign I think. Can we clarify the term and use a single one everywhere ?

Thx

**Comment by Natim** [comment]
There is three things : 

  - `state` which is a random string created on the relier that identify the oauth dance
  - `code` which is another random string created on the oauth ends and returned with the `state` that is used then by the relier to get the `token`
 - `token` which is the oauth token and which is then used to be connected with a FxA.

**Comment by tarekziade** [comment]
The code does not reflect this (see for instance session.token)

**Comment by leplatrem** [comment]
The notion of ``code`` should only exist in the ``trade_code`` method. It's received during the first step of authorization request:

First, you request an authorization code, which is kind of temporary, then you trade it against an access token.

See:
* http://tutorials.jenkov.com/oauth2/authorization-code-request-response.html
* https://tools.ietf.org/html/rfc6749#section-1.3.1

**Comment by rfk** [comment]
@tarekziade do the above comments clarify the situation, or should we be looking at tweaking the names in the code to make things clearer?

**Comment by Natim** [comment]
I don't know if it is relevant but for #28 I was looking to ``oauth.Client.trade_assertion`` and the name of the method was : ``oauth.Client.authorize_token``

**Comment by vladikoff** [comment]
@rfk please reopen this if we still want to tweak this
