### ISSUE TITLE
oauth.Client.get_redirect_url sometimes returning double slash in URL

### ISSUE THREAD

**Issue by pmac** [mozilla/PyFxA#73]
I haven't yet been able to track down the exact circumstances but we ran [into this issue in basket](https://github.com/mozmeao/basket/issues/188). Sometimes the URL returned by the `get_redirect_url()` method would look like `https://oauth.stage.mozaws.net/v1//authorization?scope=profile...` and this would result in a 404 response. Seems to happen regardless of the `server_url` value. I was using the values for `server_url` straight from the `constants.py` file for the `oauth` key. I'll update this if I figure anything else out. My solution for now is to build the URL myself in the basket code.

**Comment by pmac** [comment]
All I can guess is that something in the `urlparse` and then `urlunparse` steps is causing the extra slash to pop up. I don't see a reason it's necessary to parse the URL anyway since it's really just `server + path + query params`.

**Comment by rfk** [comment]
Looks like the low-level request-making helper was unwisely modifying `self.server_url` in-place; please take a look at https://github.com/mozilla/PyFxA/pull/74 which I suspect will fix the issue.

**Comment by rfk** [comment]
I cut a v0.7.2 release with the fix included.
