### ISSUE TITLE
"at+JWT" case mismatch between mozilla/fxa and pyfxa

### ISSUE THREAD

**Issue by jackyzy823** [mozilla/PyFxA#84]
When i using kinto-fxa. I encountered some issues. After some digging , i found that it may caused by PyFxa.
 
"at+JWT" in 
https://github.com/mozilla/fxa/blob/e440dae101bbd5d90e26dfcf60bea3edde8f362a/packages/fxa-auth-server/lib/oauth/jwt_access_token.js#L13 
do not match in case
https://github.com/mozilla/PyFxA/blob/68e576338118c0d8265f65b8003a65a77c507ef1/fxa/oauth.py#L236
which raise TrustError

should be
```python 
if jwt.get_unverified_header(token).get('typ').lower() != 'at+jwt': 
```

**Comment by rfk** [comment]
Thanks! Could you please try out the proposed fix in https://github.com/mozilla/PyFxA/pull/85 and let me know if it works for you?

**Comment by jackyzy823** [comment]
Thanks for fix.
And there may be another question
https://github.com/mozilla/PyFxA/blob/68e576338118c0d8265f65b8003a65a77c507ef1/fxa/oauth.py#L308-L310

in `scope_matches`, `authorized_scope` is assumed to be a list or tuple .
However which i get from self hosting FxA v1.178.0.  `authorized_scope`  is a **string **. 
so `scope_matches` iterates every single char of authorized_scope to match scope which obviously comes to a fail.

Reference for fxa: https://github.com/mozilla/fxa/blob/46f02be0f2e8871503401efa6b1bb44c5fdb7967/packages/fxa-auth-server/lib/oauth/jwt_access_token.js#L39

I'm not sure whether this question belongs to server or client.

**Comment by rfk** [comment]
Yes, good call; I've added [this fix](https://github.com/mozilla/PyFxA/pull/85/commits/158780465152a2e30946655f4a6b7bac9a39e349) as part of #85.

**Comment by jackyzy823** [comment]
Works like a charm. Thanks.
LGTM  :thumbsup:

**Comment by rfk** [comment]
Thanks again for your help digging into these @jackyzy823!
